kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: raytune-pong
  context: raytune-pong # raytune-pong folder
  dockerfile: ./Dockerfile

spec:
  operator: kuberay
  image: raytune-pong
  command: "python main.py"

  debug:
    jupyter: false

  tensorboard: # optional, disabled by default
    enabled: true

  types:
    Head:
      resources:
        cpus: 4
        ramRatio: 2
        accelerators: # optional
          gpu:
            count: 1
            product: t4
            type: gpu

    Workers:
      - name: cpu-workers
        count: 2
        resources:
          cpus: 4
          ramRatio: 1
          shmSizeGB: 0
